baseurl = "https://eclipse.dev/score"
DefaultContentLanguage = "en"
title = "Eclipse S-CORE"
theme = "hugo-solstice-theme"
metaDataFormat = "yaml"
disableKinds = []
enableRobotsTXT = true
pluralizeListTitles = false

[Params]
  google_tag_manager = "GTM-5WLCZXC"
  description = "The Eclipse Safe Open Vehicle Core project aims to develop an open-source core stack for Software Defined Vehicles (SDVs), specifically targeting embedded high-performance Electronic Control Units (ECUs)."
  seo_title_suffix = " | The Eclipse Foundation"
  keywords = ["eclipse", "S-CORE", "SCORE", "sdv", "software defined vehicle", "open source automotive", "automotive software", "ecu software", "embedded automotive", "iso 26262", "iso/sae 21434", "vehicle runtime", "automotive stack", "sdv platform", "real-time software", "rust automotive", "modular vehicle software", "scalable sdv", "open source", "automotive development", "functional safety", "cybersecurity compliance", "ecu integration"]
  news_count = 3
  gcse = "011805775785170369411:p3ec0igo0qq"
  gcse_result_url = "https://www.eclipse.org/home/search/"
  header_wrapper_class = "header_wrapper_class"
  call_for_action_text = "Download"
  call_for_action_url = "//eclipse.org/downloads/"
  call_for_action_icon = "fa-download"
  layout_style = "astro"
  hide_ad = false
  featured_content_publish_target = "eclipse_org"
  sidebar_layout = "default"
# js = ""
# styles = ""
# logo = ""
# favicon = ""
# share_img = ""
# logo_width = ""
# header_left_classes = ""
# main_menu_wrapper_classes = ""
# projects_working_group = ""
# show_events = true
# table_classes = "table table-bordered"
# hide_cfa_same_page = true
# show_collapsible_menu = true

[taxonomies]
  tag = "tags"

[Params.author]
  name = "Eclipse Foundation"
  website = "https://www.eclipse.org"
  email = "webdev@eclipse-foundation.org"
  facebook = "eclipse.org"
  twitter = "eclipsefdn"
  youtube = "EclipseFdn"
  googleplus = "+Eclipse"
  linkedin = "company/eclipse-foundation/"

[permalinks]
  news = "/:sections/:year/:month/:day/:slug/"

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

[[menu.sidebar]]
  name = "Documentation"
  url = "/home"
  weight = 1
  identifier = "home"

[[menu.sidebar]]
  parent ="home"
  name = "hugo-solstice-theme"
  url = "https://webdev.eclipse.org/docs/hugo/"
  weight = 1
  pre = "<i class=\"fa fa-caret-right fa-fw\"></i>"

[[menu.sidebar]]
  parent ="home"
  name = "Solstice"
  url = "https://www.eclipse.org/eclipse.org-common/themes/solstice/docs/"
  weight = 2
  pre = "<i class=\"fa fa-caret-right fa-fw\"></i>"

[[menu.sidebar]]
  parent ="home"
  name = "Hugo"
  url = "https://gohugo.io/documentation/"
  weight = 3
  pre = "<i class=\"fa fa-caret-right fa-fw\"></i>"

# Uncomment [[menu.main]] to hide the default EF menu
# or to define your own menu links.

# [[menu.main]]
